main:
  web_trigger_build_node_image:
    - runner:
         tags: cnb:arch:amd64:containerd-snapshotter
      services:
        - docker
      imports: https://cnb.cool/1Panel-dev/secrets/-/blob/main/docker-1panel-envs.yml
      stages:
        - name: set docker tag
          script: echo -n "${DOCKER_REGISTRY}/${DOCKER_GROUP}/node:$NODE_VERSION"
          exports:
            info: IMAGE_TAG
        - name: docker login
          script: docker login -u ${DOCKER_USER} -p "${DOCKER_PWD}" ${DOCKER_REGISTRY}
          
        - name: docker build and push
          script: docker buildx build 
            --platform $PLATFORM 
            --build-arg NODE_VERSION=$NODE_VERSION 
            -t $IMAGE_TAG 
            -f node/Dockerfile 
            node/ 
            --push
  web_trigger_build_php_image:
    - runner:
        tags: cnb:arch:amd64:containerd-snapshotter
      services:
        - docker
      imports: https://cnb.cool/1Panel-dev/secrets/-/blob/main/docker-1panel-envs.yml
      stages:
        - name: set docker tag
          script: echo -n "${DOCKER_REGISTRY}/${DOCKER_GROUP}/php-fpm:$PHP_VERSION"
          exports:
            info: IMAGE_TAG
        - name: docker login
          script: docker login -u ${DOCKER_USER} -p "${DOCKER_PWD}" ${DOCKER_REGISTRY}

        - name: docker build and push
          script: docker buildx build 
              --platform $PLATFORM
              -t $IMAGE_TAG 
              -f php/$PHP_VERSION/Dockerfile 
              php/$PHP_VERSION/ 
              --push